---
- name: Install Docker and remove Podman
  hosts: localhost_1
  become: true
  roles:
    - docker


- name: Deploy Docker Compose project
  hosts: localhost_1
  become: true
  vars:
    compose_project_name: myapp
    compose_template_src: templates/docker-compose.yml.j2
    compose_extra_files:
      - src: templates/app.env.j2
        dest: .env
        sensitive: true
  roles:
    - docker_compose